---

 - name: install the 'Development tools' package group
   yum:
     name: "@Development tools"
     state: present
    
 - name: Install required software
   yum:  pkg={{ item }} state=present   
   with_items:
     - openssl 
     - openssl-devel 
     - libffi 
     - libffi-devel 
     - git
     - python 
     - python-devel
     - wget
     - python-cryptography 
     - pyOpenSSL.x86_64
   when: ansible_os_family == "RedHat"

 - name: Download Ansible-Tower
   get_url:
    url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
    dest: /tmp
       
 - name: Extract Ansible-Tower
   unarchive:
    src: /tmp/ansible-tower-setup-latest.tar.gz
    dest: /tmp
    
 - name: Move minishift to /bin
   shell: mv /tmp/minishift-1.12.0-linux-amd64/minishift /bin
   
 - name: Change owner group mode of minishift
   file:
     path: /bin/minishift
     owner: root
     group: root
     mode: 0775

 - name: Download docker-machine-driver-kvm
   get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm
    dest: /tmp
    
 - name: Move docker-machine-driver-kvm to /bin
   shell: mv /tmp/docker-machine-driver-kvm /bin
   
 - name: Change owner group mode of docker-machine-driver-kvm
   file:
     path: /bin/docker-machine-driver-kvm
     owner: root
     group: root
     mode: 0775

 - name: Download Openshift client oc
   get_url:
    url: https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz
    dest: /tmp
    
 - name: Extract Openshift client oc
   unarchive:
    src: /tmp/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz
    dest: /tmp    
    
 - name: Move Openshift client oc to /bin
   shell: mv /tmp/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit/oc /bin
   
 - name: Change owner group mode of Openshift client oc
   file:
     path: /bin/oc
     owner: root
     group: root
     mode: 0775
     
 - name: Run the minishift with arguments from all
   command: /bin/minishift {{ param1 }}
   register: miniout
   
 - debug: msg="{{ miniout.stdout }}"   
